/**
 * Arquive
 *
 * Equipe desenvolvedora do sistema Arquive para Estrutura de Arquivos
 * Universidade Estadual de Campinas - 2017
 */
package archive.view;

import archive.controller.ControladorArchive;
import archive.exceptions.CabecalhoEsgotadoException;
import archive.model.Archive;
import archive.model.Cabecalho;
import archive.model.ItemCabecalho;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class TelaGerenciamento extends javax.swing.JFrame {

    private final Archive archive;

    private static final Color COR_FUNDO_BOTOES = new Color(33, 150, 243);

    private static final Color COR_LETRA_BOTOES = new Color(255, 255, 255);

    private static final Color COR_FUNDO_SELECAO = new Color(187, 222, 251);

    /**
     * Creates new form TelaInicial
     *
     * @param archive
     */
    public TelaGerenciamento(Archive archive) {
        initComponents();

        this.archive = archive;

        setLocationRelativeTo(null);

        inicializar();
    }

    private void inicializar() {
        // Adicionar listener de eventos à lista
        //lista.getSelectedValue();
        //lista.setListData(listData);
        lista.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (event.getFirstIndex() == event.getLastIndex()) {
                    // sem seleção - vazio

                    jButton2.setEnabled(false);
                    jButton4.setEnabled(false);

                } else {
                    // Find out which indexes are selected.
                    jButton2.setEnabled(true);
                    jButton4.setEnabled(true);

                    int minIndex = event.getFirstIndex();
                    int maxIndex = event.getLastIndex();

                    for (int i = minIndex; i <= maxIndex; i++) {
                        if (lista.isSelectedIndex(i)) {
                            // Item de índice i está selecionado
                        }
                    }
                }
            }
        });

        atualizarListaArquivos();
    }

    public void atualizarListaArquivos() {
        Cabecalho cabecalho = archive.getCabecalho();

        List<String> conteudoLista = new ArrayList<>();

        for (ItemCabecalho item : cabecalho.getItens()) {
            conteudoLista.add(item.getNome() + ", " + item.getTamanho());
        }

        String[] arrayItens = new String[conteudoLista.size()];
        arrayItens = conteudoLista.toArray(arrayItens);
        lista.setListData(arrayItens);
    }

    public Archive getArchive() {
        return archive;
    }

    @Override
    public void dispose() {
        try {
            ControladorArchive.fecharSessao();
        } catch (IOException ex) {
        }

        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoInserir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        botaoInserir.setBackground(COR_FUNDO_BOTOES);
        botaoInserir.setForeground(COR_LETRA_BOTOES);
        botaoInserir.setText("Inserir um arquivo");
        botaoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirActionPerformed(evt);
            }
        });
        jPanel1.add(botaoInserir);

        jButton2.setBackground(COR_FUNDO_BOTOES);
        jButton2.setForeground(COR_LETRA_BOTOES);
        jButton2.setText("Extrair selecionados");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton4.setBackground(COR_FUNDO_BOTOES);
        jButton4.setForeground(COR_LETRA_BOTOES);
        jButton4.setText("Apagar selecionados");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lista.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lista.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lista.setFixedCellHeight(20);
        lista.setSelectionBackground(COR_FUNDO_SELECAO);
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botaoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirActionPerformed
        JFileChooser selecionador = new JFileChooser();
        selecionador.setFileSelectionMode(JFileChooser.FILES_ONLY);
        selecionador.showOpenDialog(null);

        File arquivo = selecionador.getSelectedFile();

        if (arquivo == null) {
            // Nenhum arquivo selecionado
            return;
        }

        try {
            ControladorArchive.inserirArquivo(arquivo);

            atualizarListaArquivos();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Falha ao carregar arquivo");
            return;
        } catch (CabecalhoEsgotadoException ex) {
            JOptionPane.showMessageDialog(
                    null, "Não é possível adicionar mais arquivos neste archive"
            );
        }

    }//GEN-LAST:event_botaoInserirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInserir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    // End of variables declaration//GEN-END:variables
}
